# Generated by Django 3.0.5 on 2020-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalwork',
            name='source',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='musicalwork',
            name='source_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
